### ISSUE TITLE
Standard Backpack Texture Missing

### ISSUE THREAD

**Issue by Avarice** [Darkona/AdventureBackpack2#106]
Everything was looking fine up until today, when we noticed our backpack textures had disappeared.

The only things I changed were Potion ID conflicts in Blood Magic and Ars Magica 2, and some NEI filters using INPureTweaks Core.

Witchery uses defaults
Blood Magic uses 127-143
Ars Magica 2 uses 150-181

Is it possible that the potion ID changes in these mods is the culprit? I honestly didn't know whether or not (but assumed) potions had their own ID set rather than being limited to a set (i.e 1-127)

[15:47:34] [Client thread/WARN]: Failed to load texture: adventurebackpack:textures/backpack/Fatherland.png
java.io.FileNotFoundException: adventurebackpack:textures/backpack/Fatherland.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
	at com.darkona.adventurebackpack.client.render.RendererItemAdventureBackpack.renderItem(RendererItemAdventureBackpack.java:79) [RendererItemAdventureBackpack.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563) [bny.class:?]
	at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:187) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:177) [GuiContainerManager.class:?]
	at codechicken.nei.ItemPanel.draw(ItemPanel.java:129) [ItemPanel.class:?]
	at codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:196) [LayoutManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:387) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120) [bex.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38) [bfo.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bfu.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by BlackSoldierB** [comment]
It it perhaps a special day. Like Valentine. It tries to load the special texture, but it couldn't find it.
I read it somewhere on the forum

**Comment by Avarice** [comment]
I fixed it by copying /assets/textures/Standard.png and renaming the copy Fatherland.png

**Comment by ianlavr** [comment]
Where are backpack textures located?
