### ISSUE TITLE
Game crash when backpack put on

### ISSUE THREAD

**Issue by sonicringboy** [Darkona/AdventureBackpack2#115]
the game crashes when i put the backpack on through the back pack menu and i cant put it on through my inventory.

This is the mod on its own can you help?

Thank you :)

**Comment by sonicringboy** [comment]
I forgot to put the crash report so here! Good luck

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 16/04/16 17:32
Description: Updating screen events

java.lang.IndexOutOfBoundsException: -96
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.darkona.adventurebackpack.client.gui.GuiAdvBackpack.func_73864_a(GuiAdvBackpack.java:228)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.darkona.adventurebackpack.client.gui.GuiAdvBackpack.func_73864_a(GuiAdvBackpack.java:228)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: com.darkona.adventurebackpack.client.gui.GuiAdvBackpack

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Sonicringboy'/36, l='MpServer', x=244.50, y=66.62, z=64.50]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,60), Chunk: (at 4,4,12 in 15,3; contains blocks 240,0,48 to 255,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 965 game time, 965 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 118 total; [EntitySkeleton['Skeleton'/6145, l='MpServer', x=297.50, y=39.00, z=92.50], EntityZombie['Zombie'/1538, l='MpServer', x=302.50, y=16.00, z=55.03], EntitySpider['Spider'/2075, l='MpServer', x=272.50, y=23.00, z=50.50], EntityCreeper['Creeper'/1587, l='MpServer', x=288.50, y=15.00, z=51.50], EntityBat['Bat'/568, l='MpServer', x=323.34, y=28.65, z=77.44], EntitySquid['Squid'/68, l='MpServer', x=181.28, y=59.31, z=77.22], EntitySquid['Squid'/69, l='MpServer', x=186.28, y=61.34, z=75.34], EntityCreeper['Creeper'/2117, l='MpServer', x=324.44, y=16.00, z=88.03], EntitySquid['Squid'/70, l='MpServer', x=181.06, y=61.31, z=76.28], EntitySquid['Squid'/71, l='MpServer', x=188.84, y=59.06, z=75.47], EntitySkeleton['Skeleton'/1607, l='MpServer', x=251.50, y=28.00, z=113.50], EntitySquid['Squid'/72, l='MpServer', x=182.97, y=60.75, z=77.47], EntitySkeleton['Skeleton'/5708, l='MpServer', x=261.03, y=17.00, z=135.44], EntitySquid['Squid'/78, l='MpServer', x=182.59, y=58.16, z=91.16], EntityBat['Bat'/1105, l='MpServer', x=295.43, y=27.83, z=84.72], EntityBat['Bat'/4694, l='MpServer', x=267.02, y=24.81, z=32.42], EntityBat['Bat'/4695, l='MpServer', x=264.36, y=25.39, z=31.44], EntitySquid['Squid'/92, l='MpServer', x=204.50, y=58.38, z=125.09], EntitySquid['Squid'/96, l='MpServer', x=209.28, y=56.13, z=119.63], EntitySquid['Squid'/97, l='MpServer', x=209.38, y=56.91, z=125.25], EntitySquid['Squid'/98, l='MpServer', x=212.94, y=56.34, z=117.22], EntitySquid['Squid'/99, l='MpServer', x=201.38, y=56.81, z=114.59], EntitySquid['Squid'/102, l='MpServer', x=203.16, y=57.94, z=118.59], EntitySquid['Squid'/103, l='MpServer', x=211.78, y=55.84, z=116.09], EntitySquid['Squid'/119, l='MpServer', x=187.50, y=49.34, z=5.94], EntitySquid['Squid'/120, l='MpServer', x=188.09, y=50.31, z=13.03], EntitySquid['Squid'/121, l='MpServer', x=190.34, y=49.00, z=16.63], EntitySquid['Squid'/122, l='MpServer', x=191.94, y=49.34, z=14.78], EntitySquid['Squid'/123, l='MpServer', x=186.69, y=50.34, z=10.56], EntityZombie['Zombie'/1667, l='MpServer', x=202.50, y=21.00, z=123.50], EntityZombie['Zombie'/2182, l='MpServer', x=309.66, y=36.00, z=88.97], EntitySquid['Squid'/143, l='MpServer', x=246.22, y=57.72, z=0.28], EntityBat['Bat'/662, l='MpServer', x=269.60, y=24.00, z=47.61], EntityBat['Bat'/667, l='MpServer', x=274.46, y=23.88, z=51.17], EntityZombie['Zombie'/5787, l='MpServer', x=305.97, y=14.00, z=54.53], EntityZombie['Zombie'/5788, l='MpServer', x=315.50, y=15.00, z=55.50], EntityZombie['Zombie'/5789, l='MpServer', x=314.50, y=15.00, z=56.50], EntityCreeper['Creeper'/5790, l='MpServer', x=314.53, y=15.00, z=54.66], EntityCreeper['Creeper'/5791, l='MpServer', x=312.50, y=15.00, z=56.50], EntitySkeleton['Skeleton'/1212, l='MpServer', x=268.50, y=20.00, z=134.50], EntityBat['Bat'/708, l='MpServer', x=305.75, y=13.40, z=80.88], EntityBat['Bat'/1224, l='MpServer', x=317.01, y=32.83, z=20.73], EntitySkeleton['Skeleton'/1742, l='MpServer', x=311.38, y=11.00, z=53.16], EntityBat['Bat'/1236, l='MpServer', x=323.25, y=17.10, z=50.25], EntitySkeleton['Skeleton'/726, l='MpServer', x=306.28, y=22.00, z=-5.50], EntitySkeleton['Skeleton'/729, l='MpServer', x=313.47, y=20.00, z=-5.94], EntitySquid['Squid'/220, l='MpServer', x=284.50, y=52.66, z=125.66], EntityBat['Bat'/6368, l='MpServer', x=273.72, y=23.00, z=50.44], EntityCreeper['Creeper'/740, l='MpServer', x=297.00, y=20.00, z=103.44], EntityBat['Bat'/6374, l='MpServer', x=302.19, y=10.82, z=41.72], EntitySquid['Squid'/238, l='MpServer', x=181.22, y=61.34, z=45.56], EntityCreeper['Creeper'/1264, l='MpServer', x=310.50, y=33.00, z=22.50], EntitySquid['Squid'/240, l='MpServer', x=184.09, y=59.84, z=40.06], EntityCreeper['Creeper'/1265, l='MpServer', x=310.50, y=33.00, z=20.50], EntityCreeper['Creeper'/1266, l='MpServer', x=309.50, y=33.00, z=22.50], EntitySquid['Squid'/243, l='MpServer', x=184.25, y=57.69, z=52.13], EntityWitch['Witch'/1270, l='MpServer', x=298.50, y=36.00, z=32.50], EntityZombie['Zombie'/1271, l='MpServer', x=296.50, y=36.00, z=34.50], EntitySquid['Squid'/260, l='MpServer', x=290.28, y=57.78, z=116.97], EntitySquid['Squid'/261, l='MpServer', x=293.28, y=58.31, z=116.78], EntitySquid['Squid'/262, l='MpServer', x=300.38, y=58.38, z=115.50], EntitySquid['Squid'/263, l='MpServer', x=290.66, y=58.22, z=118.69], EntitySquid['Squid'/264, l='MpServer', x=294.25, y=58.38, z=121.25], EntitySquid['Squid'/266, l='MpServer', x=304.38, y=55.09, z=117.56], EntitySquid['Squid'/267, l='MpServer', x=301.84, y=58.31, z=114.31], EntitySquid['Squid'/268, l='MpServer', x=297.34, y=58.38, z=123.97], EntitySquid['Squid'/271, l='MpServer', x=294.63, y=57.13, z=117.69], EntityZombie['Zombie'/1317, l='MpServer', x=278.50, y=48.00, z=84.50], EntityCreeper['Creeper'/1830, l='MpServer', x=302.50, y=19.00, z=67.50], EntityZombie['Zombie'/1831, l='MpServer', x=312.13, y=16.00, z=59.38], EntityZombie['Zombie'/5932, l='MpServer', x=257.50, y=16.00, z=63.50], EntityZombie['Zombie'/5933, l='MpServer', x=259.50, y=16.00, z=63.50], EntitySkeleton['Skeleton'/5934, l='MpServer', x=259.44, y=17.00, z=71.06], EntitySquid['Squid'/308, l='MpServer', x=191.97, y=47.34, z=56.50], EntitySquid['Squid'/312, l='MpServer', x=202.88, y=46.00, z=61.72], EntitySquid['Squid'/315, l='MpServer', x=193.03, y=47.06, z=48.06], EntitySquid['Squid'/316, l='MpServer', x=190.94, y=48.34, z=58.44], EntitySquid['Squid'/318, l='MpServer', x=193.38, y=49.31, z=56.34], EntitySquid['Squid'/319, l='MpServer', x=203.50, y=47.00, z=57.88], EntityCreeper['Creeper'/1865, l='MpServer', x=234.50, y=38.00, z=-10.50], EntityCreeper['Creeper'/1866, l='MpServer', x=233.50, y=38.00, z=-8.50], EntitySquid['Squid'/331, l='MpServer', x=220.13, y=62.00, z=26.34], EntitySquid['Squid'/333, l='MpServer', x=215.66, y=62.31, z=26.38], EntitySquid['Squid'/334, l='MpServer', x=220.47, y=62.38, z=19.47], EntitySquid['Squid'/335, l='MpServer', x=227.25, y=62.34, z=21.50], EntitySquid['Squid'/336, l='MpServer', x=224.03, y=62.31, z=19.41], EntitySquid['Squid'/337, l='MpServer', x=221.63, y=62.09, z=22.63], EntitySkeleton['Skeleton'/1392, l='MpServer', x=173.50, y=32.00, z=130.50], EntitySquid['Squid'/369, l='MpServer', x=183.41, y=48.91, z=50.66], EntitySkeleton['Skeleton'/1393, l='MpServer', x=176.50, y=32.00, z=129.50], EntitySquid['Squid'/370, l='MpServer', x=183.25, y=47.34, z=42.19], EntitySkeleton['Skeleton'/1394, l='MpServer', x=175.50, y=32.00, z=131.50], EntitySquid['Squid'/372, l='MpServer', x=181.72, y=48.91, z=54.31], EntitySquid['Squid'/374, l='MpServer', x=183.56, y=48.34, z=51.84], EntitySquid['Squid'/376, l='MpServer', x=187.97, y=49.38, z=52.66], EntitySquid['Squid'/377, l='MpServer', x=184.50, y=48.34, z=49.50], EntityCreeper['Creeper'/1913, l='MpServer', x=307.63, y=12.00, z=50.00], EntitySquid['Squid'/378, l='MpServer', x=185.25, y=48.34, z=43.50], EntitySquid['Squid'/379, l='MpServer', x=187.84, y=47.81, z=39.22], EntitySkeleton['Skeleton'/1915, l='MpServer', x=298.91, y=11.00, z=48.50], EntitySquid['Squid'/440, l='MpServer', x=193.72, y=61.06, z=114.13], EntitySquid['Squid'/441, l='MpServer', x=186.50, y=61.34, z=115.47], EntitySquid['Squid'/442, l='MpServer', x=186.47, y=59.03, z=123.38], EntitySquid['Squid'/444, l='MpServer', x=183.19, y=61.38, z=121.25], EntitySquid['Squid'/445, l='MpServer', x=187.09, y=61.34, z=117.03], EntitySquid['Squid'/446, l='MpServer', x=184.72, y=59.06, z=123.91], EntitySquid['Squid'/449, l='MpServer', x=184.63, y=61.34, z=118.78], EntitySquid['Squid'/451, l='MpServer', x=183.75, y=60.94, z=127.81], EntityBat['Bat'/1487, l='MpServer', x=317.11, y=31.79, z=11.33], EntityBat['Bat'/1493, l='MpServer', x=261.82, y=24.13, z=33.63], EntityBat['Bat'/1514, l='MpServer', x=305.28, y=53.00, z=84.56], EntityWitch['Witch'/6639, l='MpServer', x=319.51, y=32.16, z=18.51], EntityWitch['Witch'/6640, l='MpServer', x=317.50, y=32.00, z=22.50], EntityWitch['Witch'/6641, l='MpServer', x=321.50, y=32.00, z=21.50], EntitySkeleton['Skeleton'/6642, l='MpServer', x=324.53, y=32.00, z=15.50], EntitySkeleton['Skeleton'/6643, l='MpServer', x=323.50, y=32.00, z=18.50], EntityClientPlayerMP['Sonicringboy'/36, l='MpServer', x=244.50, y=66.62, z=64.50], EntitySkeleton['Skeleton'/6644, l='MpServer', x=323.50, y=32.00, z=19.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 187274880 bytes (178 MB) / 359497728 bytes (342 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.1001' Renderer: 'AMD Radeon HD 8600/8700M'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8600/8700M GL version 4.5.13431 Compatibility Profile Context 16.150.2211.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [YoutubersSkin]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by sonicringboy** [comment]
it does work through shift break

**Comment by Jomarai** [comment]
did you ever figure out how to fix this cause im having the same issue
