### ISSUE TITLE
trying to open a backpack crashes the game

### ISSUE THREAD

**Issue by JokerReaper** [Darkona/AdventureBackpack2#33]
as the title reads, im not sure if it has anything to do with what the backpack had in the tanks or inventory, but i only had 2000 of water in one tank, also when i put the mouse over the bag it says i have 2000 in both tanks, but i press the key for the inventory for the backpack (the bat pack) & this is what i get after it crashes i hope it helps. i also have a suggestion about certain ways to get the back gui to work as its own part, instead of in the armor slot, theres a mod called crafting dead, that added another tab to hold the packs & it also rendered on the player, & was able to open the bag without putting it down like this one here, granted it means added another gui to the mix, but its might solve some other issues as well. if youre already thinking about doing that, or have another idea on how you want to go about it, like i said its only a suggestion, anyways thats all thanks :)
Update; i tried to figure out whats causing it & it seems to be the water being in the pack, i tried on my test map & added a bucket of water while the pack's gui was open & it crashed, just like before sorry i have a thing for trying figure out bugs & what cause em

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 1/6/15 5:09 AM
Description: Rendering screen

java.lang.AbstractMethodError: com.darkona.adventurebackpack.client.gui.GuiAdvBackpack.drawTexturedModelRectFromIcon(IILnet/minecraft/util/IIcon;II)V
	at com.darkona.adventurebackpack.client.gui.GuiTank.drawMethodOne(GuiTank.java:107)
	at com.darkona.adventurebackpack.client.gui.GuiTank.draw(GuiTank.java:74)
	at com.darkona.adventurebackpack.client.gui.GuiAdvBackpack.func_146979_b(GuiAdvBackpack.java:132)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1354)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Darkona** [comment]
In the config file, select method 3 for the tank rendering, while I fix methods one and two.

**Comment by Darkona** [comment]
Fixed for next version :)
