### ISSUE TITLE
AdventureBackpack mod crashing when loading

### ISSUE THREAD

**Issue by BlueYoshi68** [Darkona/AdventureBackpack2#35]
Time: 1/9/15 11:57 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: -1
	at com.darkona.adventurebackpack.util.calendar.ChineseCalendar.sectionalTerm(ChineseCalendar.java:334)
	at com.darkona.adventurebackpack.util.calendar.ChineseCalendar.computeSolarTerms(ChineseCalendar.java:326)
	at com.darkona.adventurebackpack.util.calendar.ChineseCalendar.isChineseNewYear(ChineseCalendar.java:60)
	at com.darkona.adventurebackpack.AdventureBackpack.preInit(AdventureBackpack.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at

**Comment by Darkona** [comment]
Download latest version o.o

**Comment by BlueYoshi68** [comment]
I did 1.7.10 from skydaz

**Comment by BlueYoshi68** [comment]
it doesn't work
it crashes as soon as it loads

**Comment by Darkona** [comment]
If you are downloading from an unofficial source there's no way you'll be sure to get an updated version. Go here and use the download link: https://github.com/Darkona/AdventureBackpack2/wiki
