### ISSUE TITLE
Drinking in MP causes client to instantly drop from server

### ISSUE THREAD

**Issue by twothe** [Darkona/AdventureBackpack2#53]
When drinking water in multiplayer while another player is nearby the drinker will instantly disconnect with an internal server error. There is no error entry or crash log anywhere that I could find, but the bug is 100% reproducible.

**Comment by Darkona** [comment]
Most recent version? I'm confused about this and can't find a way to approach it. Without it giving logs it just makes it even more confusing.

**Comment by twothe** [comment]
Using Beta-0.8b on server with default settings except for PvP disabled. I show off the adventure backpack to a friend and explain that he can even drink with the hose. He tries it and gets instantly disconnected from the server. He joins back in and I try to drink and get instantly disconnected as well. The bug is 100% reproducible.

I checked the log files an there was no report at all.

**Comment by cluckinator** [comment]
I have experienced the same issue and I noticed: If I drink milk or something else consumable, it works fine. If I try to drink water or lava or oil, I get an instant crash to desktop with no log. I am using version 0.8B.

**Comment by dodzh** [comment]
i have same issue:
here is a copy of my log
"[08:59:10] [Server thread/WARN]: Failed to handle packet for /***.***.***.5:57782
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerM
P.java:349) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPl
ayServer.java:303) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(Sourc
eFile:137) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(Sourc
eFile:8) ~[jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java
:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:
165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
Caused by: java.lang.NoSuchFieldError: field_70118_ct
        at com.darkona.adventurebackpack.fluids.effects.WaterEffect.affectDrinke
r(WaterEffect.java:30) ~[WaterEffect.class:?]
        at com.darkona.adventurebackpack.fluids.FluidEffectRegistry.executeFluid
EffectsForFluid(FluidEffectRegistry.java:111) ~[FluidEffectRegistry.class:?]
        at com.darkona.adventurebackpack.common.ServerActions.setFluidEffect(Ser
verActions.java:95) ~[ServerActions.class:?]
        at com.darkona.adventurebackpack.item.ItemHose.func_77654_b(ItemHose.jav
a:426) ~[ItemHose.class:?]
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:151) ~[add.c
lass:?]
        at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.ja
va:419) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerM
P.java:866) ~[mw.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.j
ava:242) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerM
P.java:295) ~[mw.class:?]
        ... 10 more
[08:59:10] [Server thread/INFO]: Dodzh lost connection: TextComponent{text='Inte
rnal server error', siblings=[], style=Style{hasParent=false, color=null, bold=n
ull, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=
null}}
[08:59:10] [Server thread/INFO]: D********** left the game"

also drinking effects dont work

Forge version 10.13.4.1448
MC V 1.7.10

**Comment by Darkona** [comment]
Reworking the way fluids apply effects. Fix on next release.
