### ISSUE TITLE
server crash with UUID and makeHorsesFollowOwner

### ISSUE THREAD

**Issue by LemADEC** [Darkona/AdventureBackpack2#99]
Our server is crashing due to invalid UUID string related to makeHorsesFollowOwner in adventurebackpack-1.7.10-0.8c.

Strangely, GeneralEventHandler.java:123 doesn't match with the source code provided on github?

```
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/25/15 11:05 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(UUID.java:194)
	at com.darkona.adventurebackpack.handlers.GeneralEventHandler.makeHorsesFollowOwner(GeneralEventHandler.java:123)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_GeneralEventHandler_makeHorsesFollowOwner_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72868_a(World.java:3961)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1020)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.UNOFFICIAL
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.7.0_85, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2006252664 bytes (1913 MB) / 3060203520 bytes (2918 MB) up to 5100273664 bytes (4864 MB)
	JVM Flags: 20 total; -Xms3G -Xmx5G -XX:ParallelGCThreads=2 -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc -Xss4M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 113 mods loaded, 113 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.UNOFFICIAL.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.UNOFFICIAL.jar) 
	UCHIJAAAA	kimagine{0.1} [KImagine] (minecraft.jar) 
	UCHIJAAAA	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	gasesCore{1.6.2} [Glenn's Gases Core] (minecraft.jar) 
	UCHIJAAAA	gasesFrameworkCore{1.1.2} [Gases Framework Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.4.6-pre2} [AgriCraft] (AgriCraft-1.7.10-1.4.6-pre2.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	DCsAppleMilk{1.7.10_2.8o} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.8o.jar) 
	UCHIJAAAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.8o.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.38.1.98} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	Grinder{4.0.0} [Grinder] (AttachableGrinder-4.0.0.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Automagy{0.27} [Automagy] (Automagy-1.7.10-0.27.jar) 
	UCHIJAAAA	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	Botania{r1.8-245} [Botania] (Botania r1.8-245.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.10} [Brandon's Core] (BrandonsCore-1.0.0.10-bugfix.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	doggytalents{v1.9.0h} [Doggy Talents] (DoggyTalents-1.7.10-v1.9.0h-universal.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2-snapshot_9} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore-1.13.jar) 
	UCHIJAAAA	essentialcraft{4.6.1710.63} [Essential Craft 3] (EssentialCraftv4.6.1710.63.jar) 
	UCHIJAAAA	essenthaum{1.1.1710.0} [Essential Thaumaturgy] (essentialthaum-1.1.1710.11.jar) 
	UCHIJAAAA	evilcraft{0.9.2} [EvilCraft] (EvilCraft-1.7.10-0.9.2.jar) 
	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.2-19.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJAAAA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCHIJAAAA	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.572} [Forbidden Magic] (Forbidden Magic-1.7.10-0.572.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	gasesFramework{1.1.2} [Gases Framework] (gasesFramework-1.7.10-1.1.2.jar) 
	UCHIJAAAA	gases{1.6.2} [Glenn's Gases] (gases-1.7.10-1.6.2.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.3.8} [Inventory Pets] (inventorypets-1.7.10-1.3.8-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	lance{2.6.1.1710} [Lance Mod] (lance-2.6.1.1710.jar) 
	UCHIJAAAA	reaper_lantern{1.47} [Lantern mod] (Lantern1.47[1.7.10].jar) 
	UCHIJAAAA	levelup{0.10} [Level Up!] (LevelUp!-0.10(1.7.10).jar) 
	UCHIJAAAA	llibrary{0.6.2} [LLibrary] (llibrary-0.6.2-1.7.10.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJAAAA	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
	UCHIJAAAA	magicalcropsdeco{4.0.0_PUBLIC_BETA_4a} [Magical Crops: Decorative] (magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar) 
	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.1.1.0} [Minecraft Comes Alive] (MCA-1.7.10-5.1.1.0-universal.jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCHIJAAAA	AS_Minions{1.9.4} [Minions] (Minions-1.7.10.jar) 
	UCHIJAAAA	mowziesmobs{1.2.5-undefined} [Mowzie's Mobs] (Mowzie's Mobs-1.2.6.jar) 
	UCHIJAAAA	AS_MultiMine{1.4.4} [Multi Mine] (MultiMine-1.7.10.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	pchan3{0.7} [PChan3 mods] (PChan3Mods-0.7(1.7.10).jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCHIJAAAA	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
	UCHIJAAAA	DustMod{2.0.0} [Runic Dust Mod] (Runic-Dust-Mod-1.7.10-2.0.4.jar) 
	UCHIJAAAA	DustExample{1.0} [Dust Mod Example 1] (Runic-Dust-Mod-1.7.10-2.0.4.jar) 
	UCHIJAAAA	DustModDefaults{1.6.1} [Dust mod default Rune Pack] (Runic-Dust-Mod-1.7.10-2.0.4.jar) 
	UCHIJAAAA	DustModTestPack{0.03} [Dust mod Test pack] (Runic-Dust-Mod-1.7.10-2.0.4.jar) 
	UCHIJAAAA	Sampler{1.39} [Sampler] (sampler-1.39.jar) 
	UCHIJAAAA	SanguineExtras{1.3.2} [Sanguine Utilities] (Sanguine Utilities-1.3.2.jar) 
	UCHIJAAAA	SSR{rc3} [Soul Shards Reborn] (SSR-rc3.jar) 
	UCHIJAAAA	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) 
	UCHIJAAAA	TaintedMagic{1.1.6.4} [Tainted Magic] (TaintedMagic-1.1.6.4.jar) 
	UCHIJAAAA	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAAAA	elysium{1.0} [The Elysium] (TheElysium-1.7.x-1.0.3.jar) 
	UCHIJAAAA	erebus{0.4.1} [Erebus] (TheErebus-0.4.1.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	vending{1.2.3} [vending] (vending-v1.2.3.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 50; [EntityPlayerMP['Leolele99'/106609, l='Merlin', x=1569.33, y=86.00, z=-455.24](Leolele99 at 1569.3255345786588,86.0,-455.2380470768424)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by isinfinity** [comment]
I have that crash before.I REINSTALL the mod but that leas to another crash.You can try it though.

**Comment by LemADEC** [comment]
we've switched to a custom compilation of the mod to fix that mod among a few others
